issue-2-add-location | Samuel Cho
Samuel-Cho/teeter-taste pull request #16
Opened 2021-04-07 23:50 UTC by Samuel-Cho

Issue 2: User can add a location. 

<img width="1430" alt="Screen Shot 2021-04-07 at 4 20 01 PM" src="https://user-images.githubusercontent.com/76749207/113948261-4f4f2000-97c1-11eb-9c55-8e85f046597e.png">
<img width="356" alt="Screen Shot 2021-04-07 at 4 20 09 PM" src="https://user-images.githubusercontent.com/76749207/113948273-51b17a00-97c1-11eb-827c-eec6b89ca05d.png">

2021-04-07 23:56 UTC, thebearingedge requested changes
Please see my note in the code. Also, please add more functionality to your form. At least when the user submits the form, it should switch screens and update the URL hash.

2021-04-07 23:56 UTC, thebearingedge commented on client/components/search-form.jsx
> +              onChange={this.handleChange} />
Your inputs need a `value` prop.

2021-04-08 18:26 UTC, Samuel-Cho commented
<img width="741" alt="Screen Shot 2021-04-08 at 11 19 04 AM" src="https://user-images.githubusercontent.com/76749207/114077655-e4532700-985c-11eb-8e8b-02790123816a.png">
<img width="451" alt="Screen Shot 2021-04-08 at 11 19 31 AM" src="https://user-images.githubusercontent.com/76749207/114077670-e74e1780-985c-11eb-8db5-4f79e196c35c.png">
<img width="1191" alt="Screen Shot 2021-04-08 at 11 20 21 AM" src="https://user-images.githubusercontent.com/76749207/114077675-e7e6ae00-985c-11eb-8cc6-79da94e4b0f0.png">

2021-04-08 20:01 UTC, Samuel-Cho commented
<img width="712" alt="Screen Shot 2021-04-08 at 12 42 33 PM" src="https://user-images.githubusercontent.com/76749207/114088977-77df2480-986a-11eb-8149-70dbffa688a5.png">
<img width="1414" alt="Screen Shot 2021-04-08 at 12 42 57 PM" src="https://user-images.githubusercontent.com/76749207/114088986-7c0b4200-986a-11eb-9502-234eceffb277.png">

2021-04-08 20:08 UTC, thebearingedge requested changes

2021-04-08 20:08 UTC, thebearingedge commented on client/components/search-form.jsx
> +      });
Are you sure you need both of these? I think the second one with the `if` in the `.map()` is enough.

2021-04-08 20:22 UTC, Samuel-Cho commented
<img width="700" alt="Screen Shot 2021-04-08 at 1 15 54 PM" src="https://user-images.githubusercontent.com/76749207/114091365-7400d180-986d-11eb-81e9-b5978debd45c.png">

2021-04-08 20:34 UTC, thebearingedge approved these changes

2021-04-08 21:32 UTC, merged